config/routes.rb
VirtualSchool::Application.routes.draw do
  

  get "pages/home"

  get "pages/about"

  get "pages/contact"

  get "pages/help"
  
  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/help', :to => 'pages#help'
  match '/search', :to => 'videos#search'

  resources :questions

  resources :answers

  root :to => 'pages#home'

  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy', via: :delete

  resources :sessions, :only => [:new, :create, :destroy]

  resources :users
  match '/signup', :to => 'users#new'

  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :question
	validates :content, presence: true
	
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  #opinio
end

app/models/question.rb
class Question < ActiveRecord::Base
	#acts_as_commentable
	#opinio_subjectum
	acts_as_indexed :fields => [:title, :desc]
	attr_accessible :title, :desc
    validates :user_id, presence: true
    validates :title, presence: true

    belongs_to :user
    has_many :answers
    
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
	attr_accessible :name, :email, :password, :password_confirmation
	has_secure_password
	has_many :questions
	
	before_save :create_remember_token
	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :name, :presence => true, :length => {:maximum => 50}
	validates :email, :presence => true,
					  :format => {:with => email_regex},
					  :uniqueness => {:case_sensitive => false}

	validates :password, length: {minimum: 6}
	validates :password_confirmation, presence: true

	private

	def create_remember_token
		self.remember_token = SecureRandom.urlsafe_base64
	end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	def create
			#@answer = @question.answers.build(params[:answer])
			#@answer = Answer.new (params[:answer][:question_id])
			@answer = Answer.new(params[:answer]) 
		if @answer.save
			flash[:success] = "Answer Posted Successfully"
			redirect_to root_path
			#redirect_to @answer
		else
			redirect_to 'users/show'
		end
		
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  	

  def home
    @question = current_user.questions.build if signed_in?
    # render 'users/show' 	
  end

  def about
  end

  def contact
  end

  def help
  end
  
  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	def index
		@questions = Question.all
		#@questions = Question.paginate(:page => params[:page], :per_page => 10)
	end

	def create
		@question = current_user.questions.build(params[:question])
		if @question.save
			flash[:success] = "Question Posted Successfully"
			redirect_to root_path
		else
			render 'users/show'
		end
	end

	def show
		@question = Question.find(params[:id])
        #if signed_in?
 		#	@user_who_commented = @current_user
        #	@comment = Comment.build_from( @question, @user_who_commented.id, "Hey guys this is my comment!" )
		#end
		@answer = @question.answers.build if signed_in?
	end

	def destroy
		
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	@title = "Sign In"
  end

  def create
  	user = User.find_by_email(params[:session][:email])
  	if user && user.authenticate(params[:session][:password])
  		# Sign the user and redirect to its profile page
			sign_in user
			redirect_to user
		else
			# Error! render the sign in page with some error message
			flash.now[:error] = "Invalid Username/Password combination"
			@title = "Sign in"
		  render 'new'
		end

  end

	def destroy
		sign_out
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :signed_in_user, only: [:edit, :update]
	before_filter :correct_user, only: [:edit, :update]
  def show
  	@user = User.find(params[:id])
  	@title = @user.name
    @questions = @user.questions
    @questions_asked = @user.questions
  end

  def new
  	@user = User.new
  	@title = "Sign up"
  end

  def create
  	@user = User.new(params[:user])
  	if @user.save
  		#saved successfully
  		sign_in @user
  		flash[:success] = "Welcome to Virtual School!"
  		redirect_to @user
  	else
  		@title = "Sign up"
  		render 'new'
  	end
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
		@user = User.find(params[:id])
		if @user.update_attributes(params[:user])
			flash[:success] = "Profile Updated Successfully"
			sign_in @user
			redirect_to @user
		else
			render 'edit'
		end
  end
  
  private

  def signed_in_user
  	redirect_to signin_path, notice: "Please Sign in" unless signed_in?
  end
  def correct_user
  	@user = User.find(params[:id])
  	redirect_to(root_path) unless current_user?(@user)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	
	def search
		keyword = params[:keyword]
		# @videos = YoutubeSearch.search(keyword, :page => 10, :per_page => 4).first
		@videos = YoutubeSearch.search(keyword,'max-results' => '4', 'start-index' => '1')
		@related_questions = Question.find_with_index(keyword)
	end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title
		base_title = "Virtual School"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"	
		end
	end		
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		@current_user ||= user_from_remember_token
	end

	def current_user_method
		@current_user ||= user_from_remember_token
	end	

	def current_user?(user)
		user == current_user
	end

	private

	def user_from_remember_token
		remember_token = cookies[:remember_token]
		User.find_by_remember_token(remember_token) unless remember_token.nil?
	end
	def sign_out
		current_user = nil
		cookies.delete(:remember_token)
	end
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/answers/_answer.html.erb
 <div class="answer-box">
	<%= title = answer.content %>
	<p> answered by <%= answer.owner_id%></p>
 </div>

app/views/layouts/_footer.html.erb
<!--<div class="container">
	<footer>
			<p><em> &copy; 2012 Some Rights Reserved!</em></p>
	</footer>
</div> -->	

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" id="logo" href="/">Virtual School</a>
          <div class="nav-collapse">
            <ul class="nav pull-right">
              <li class="active"><a href="/">Home</a></li>
              <li><%= link_to "Questions","/questions" %></li>
              <li><%= link_to "About",about_path %></li>
              <li><%= link_to "Contact",contact_path %></li>
              <li><%= link_to "Help",help_path %></li>
              <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
            </ul>
          </div>
        </div>
      </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "pages", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  
  <script type="text/javascript">
    $(function () {
    $("a.youtube").YouTubePopup({ autoplay: 0 });
});    
    $.fn.YouTubePopup.defaults = {
    'youtubeId': '',
    'title': '',
    'idAttribute': 'rel',
    'draggable': false,
    'modal': true,
    'width': 840,
    'height': 600,
    'hideTitleBar': true,
    'clickOutsideClose': true,
    'overlayOpacity': 0.5,
    'autohide': 2,
    'autoplay': 1,
    'color': 'red',
    'color1': 'FFFFFF',
    'color2': 'FFFFFF',
    'controls': 1,
    'fullscreen': 1,
    'loop': 0,
    'hd': 1,
    'showinfo': 0,
    'theme': 'light'
};

  </script>
  
</head>
<body>
  <%= render 'layouts/header' %>
    <div class="container" id="primary-stuffs">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      
    </div>
    <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/pages/about.html.erb
<div class="container primary-stuffs">
<p>Virtual School where you can search video tutorials, ask questions or doubts, answer/disqus questions and    problems..
                          many other cool stuffs to speed up your Learning process! <strong> and of course you will have a lot 
                           of Fun doing that.</strong></p>
<h1>Why Virtual School ?</h1>
<div class="tabbable">
    							<ul class="nav nav-tabs">
    								<li class="active"><a href="#1" data-toggle="tab">Learn</a></li>
    								<li><a href="#2" data-toggle="tab">Share</a></li>
								<li><a href="#3" data-toggle="tab">Have Fun</a></li>
    							</ul>
    							<div class="tab-content">
    								<div class="tab-pane active" id="1">
    									<p>Because, It's Easy to Learn from Video Tutorials, available freely from the 
									reputed YouTube Channels like Khan Academy</p>
									<img src="http://www.2webvideo.com/images/learning-video-easy-fun.jpg" alt="learn from video"/>
    								</div>
    								<div class="tab-pane" id="2">
    									<p>Q&A provides an easy platform to share and discuss things together with your 
									friends in a much better way! </p>
									<img src = "http://www.dailyblogtips.com/wp-content/uploads/questionsandanswers.jpg" alt="q&a"/>
    								</div>
								<div class="tab-pane" id="3">
									<p>And Most important thing - it's Fun, Learning becomes more easy when it has more Fun :)</p>
									<img src="http://www.magnificentdollars2.com/wp-content/uploads/15_5_orig.gif" />							                                               	</div>	
                     					</div>
    						</div> 
</div>                            

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
 
          <div class="row-fluid">   
             <div class="span4" id="video-search">
                        <h4>Search Videos</h4>
               <form action = "/search" id="yt-search-box">
                          <input type="text" name="keyword" id="ytSearchBox" placeholder="Type and Hit Enter" required/>
                       </form> 
                            </div>   
                              
             
           <div class="span8" id="qa">

                    <h4>Help Contents</h4>
                    <br />
                    <a class="btn">Do you Really Need Help ?</a></p>
           </div>
          </div> 

app/views/pages/home.html.erb
  <div class="row-fluid">   
             <div class="span4" id="video-search">
    				    <h4>Search</h4>
               <form action = "/search" id="yt-search-box">
                          <input type="text" name="keyword" id="ytSearchBox" placeholder="Type and Hit Enter" required/>
                       </form> 
					   </div>   
					     
             
           <div class="span8" id="qa">

              <% if signed_in? %>
                <div class="span4">

                  <section>
                    <%= render 'shared/user_info' %>
                  </section>
                  <section>
                    <%= render 'shared/question_form' %>
                  </section>

                </div>

              <% else %>
                  <%= image_tag('any-questions.jpg') %>

                 <%= link_to "Signup Now",signup_path, class: "btn btn-large btn-primary" %>

              <% end %>

           </div>
  </div> 
 

app/views/questions/_question.html.erb
<li>
	<% title = question.title %>
	<% id = question.id %>
	<span class="content"><%= link_to "#{title}","/questions/#{id}" %> </span>
	<span class="timestamp"> Asked <%= time_ago_in_words(question.created_at)%> ago</span>
</li>

app/views/questions/index.html.erb
 <div class="row-fluid">     

  <div class="span4" id="video-search">
    				    <h4>Search</h4>
               <form action = "/search" id="yt-search-box">
                          <input type="text" name="keyword" id="ytSearchBox" placeholder="Type and Hit Enter" required/>
                       </form> 
  </div>  


  <div class="span8">
    <% if @questions.any? %>
      	<h3>Questions Asked</h3>
      		<ol class="questions">
      			<%= render @questions %>
      		</ol>
      		
    <% end %>
  </div>


  </div> 

 
     

app/views/questions/show.html.erb
<div class="row-fluid">     

  <div class="span4" id="video-search">
                        <h4>Search</h4>
               <form action = "/search" id="yt-search-box">
                          <input type="text" name="keyword" id="ytSearchBox" placeholder="Type and Hit Enter" required/>
                       </form> 
  </div> 



 <div class="span8">
	<div id="question-top">	
		<h2> Q. <%= @question.title %></h2>
    	<%= @question.desc %>
    	<div class="asker">Asked By <%= @question.user.name %></div>
    </div>	
    <hr />
    <h3>Answers</h3>
    <% if @question.answers.any? %>
      <div class="answers" style="display:block, color:#333; padding:5px, margin: 10px;">
        <%= render @question.answers %>
      </div> 
    <% else%>
        <p>Nobody has answered yet!</p>
    <% end%>
    <h4> Add Your Answer</h4>
    <% if signed_in? %>

         <%= render 'shared/answer_form' %>
    <% else %>    
        <p> You need to sign in to reply</p>
    <% end %>	
    

  </div>
 </div> 

app/views/shared/_answer_form.html.erb
<%= form_for @answer do |f| %>
            
            <%= f.text_area :content, :placeholder => "Reply", :rows => "8", required: "required" %>
            <%= f.hidden_field :owner_id, :value => current_user.id %>
            <%= f.hidden_field :question_id, :value => @question.id %>
            <%= f.submit "POST", class: "btn btn-large btn-primary" %>
 <% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li> <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_question_form.html.erb
<%= form_for @question do |f| %>
  
  <div class="field">
    <%= f.text_field :title, placeholder: "Type Your Question ?", required: "required" %>
    <%= f.text_area :desc, placeholder: "Describe Your question in detail", :rows => "5", required: "required" %>
  </div>
  <%= f.submit "POST", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>"> <%= gravatar_for current_user %> </a>

<h1><%= current_user.name %></h1>

<span><%= link_to "View My Profile" %></span>

<span></span>

app/views/users/edit.html.erb
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
  <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', :object => f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <br />

      <%= f.submit "Save changes", :class => "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
      <br />
      <%= f.submit "Create My Account", :class => "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">

<table class="profile" summary="profile inforrmation">
	<tr>
		<td class="main">
			<h1>
       <%= gravatar_for @user %>
	     <%= @user.name %>
      </h1>
		</td>
		<td class="sidebar round">
			<strong>Name</strong> <%= @user.name %> <br />
			<strong>URL</strong> <%= link_to user_path(@user), @user %><br />
			<strong>Contact</strong> <%= @user.email %> <br />
		</td>
	 <tr>
</table>
	<div class="span8">
    <% if @user.questions.any? %>
      	<h3>Questions(<%= @user.questions.count %>) Asked By <%= @user.name %> </h3>
      		<ol class="questions">
      			<%= render @questions %>
      		</ol>
      		 	
    <% end %>
  </div>
 </div> 
 

app/views/videos/search.html.erb
         <div class="row-fluid">
    			<div class="span4" id="video-search">
    				   <h4>Search</h4>
				       <form action = "/search" id="yt-search-box">
                          <input type="text" name="keyword" id="ytSearchBox" placeholder="Type and Hit Enter" required/>
                       </form>
                     <div id="video-results">
                         <h3>Video Results</h3>
                       <ol>
   
                           <% @videos.each do |video| %>
                              <% video_id = video['video_id']
                              url = "http://www.youtube.com/watch?v="+video_id 
                              thumbnail_url = "http://img.youtube.com/vi/"+video_id+"/1.jpg"
                              vid_id_quoted = '"'+video_id+'"' %>
                              <li> <%= link_to "#{video['title']}",'#', :rel => "#{video_id}", :class =>'youtube' %> </li>
                             
                             <%= link_to image_tag("#{thumbnail_url}"),'#',:rel => "#{video_id}", :class =>'youtube' %>
                             <!-- <img src=<%="#{thumbnail_url}" %> style=""/>
                             <a class="youtube" rel="4eYSpIz2FjU" href="#">Click me</a> -->
                             <br />
                           <% end %>
                      </ol> 
                    </div>   
                
				</div>   
    				
					     
             
              <div class="span8" id="qa">
                <h4>Possibly Related Questions</h4>
                <div class="answer-box">
                  <% if @related_questions.nil? %>
                    <p>No Match Found</p>
                  <% else %>
                  <ul>
                    <% @related_questions.each do |q| %>
                    <li>
                        <% title = q.title %>
                        <% id = q.id %>
                        <% @asker = q.user %>
                        <% @name  = q.user.name %>
                        <span class="content"><%= link_to "#{title}","/questions/#{id}" %> </span>
                        <span class="timestamp"> Asked <%= time_ago_in_words(q.created_at)%> ago by <strong><%= link_to "#{@name}",@asker %></strong></span>
                    </li>
                    <% end%>
                  </ul>  
                <% end%>
                  
              </div> <!-- end of qa -->
		
           </div> <!-- End of row Fluid -->